// JavaScript Document
document.writeln("<div class=\'footer\'>");
document.writeln("<div class=\'footer-top\'>");
document.writeln("	<ul>");
document.writeln("		<li class=\'fl\'>");
document.writeln("			<img src=\'images/zhandian/bz1.PNG\'>");
document.writeln("			<span>正品保障</span>");
document.writeln("		</li>");
document.writeln("		<li class=\'fl\'>");
document.writeln("			<img src=\'images/zhandian/bz2.PNG\' />");
document.writeln("			<span>放心购物</span>");
document.writeln("		</li>");
document.writeln("		");
document.writeln("		<li class=\'fl\'>");
document.writeln("			<img src=\'images/zhandian/bz3.PNG\' />");
document.writeln("			<span>快速物流</span>");
document.writeln("		</li>");
document.writeln("		");
document.writeln("		<li class=\'fl\'>");
document.writeln("			<img src=\'images/zhandian/bz4.PNG\' />");
document.writeln("			<span>上门退还</span>");
document.writeln("		</li>");
document.writeln("	</ul>");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=\'footer-middle\'>");
document.writeln("    <div class=\'middle\'>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>关于艾米</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>企业荣誉</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>艾米体验店</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>代理商专区</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>加入艾米</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>联系我们</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>供应/服务商需求咨询</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>新闻资讯</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>艾米新闻</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>媒体报道</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>购物指南</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>购物流程</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>支付方式</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>配送说明及费用</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>订单管理</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>购买常见问题</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>预置应用公示</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>售后服务</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>售后政策</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>售后服务网点</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>上门维修</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>签收须知</a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>物流查询</a></dd>");
document.writeln("		</dl>");
document.writeln("		<dl class=\'fl\'>");
document.writeln("			<dt>关注我们</dt>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>新浪微博<b></b></a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>腾讯微博<b></b></a></dd>");
document.writeln("				<dd><a href=\'#\' target=\'_blank\'>QQ空间<b></b></a></dd>");
document.writeln("		</dl>");
document.writeln("	   <div class=\'icon fl\'>");
document.writeln("		     <div class=\'weixin\'>");
document.writeln("		      </div>");
document.writeln("		<span>扫一扫关注微信</span>");
document.writeln("	    </div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=\'footer-bottom\'>");
document.writeln("	<div class=\'bottom\'>");
document.writeln("		<div class=\'m\'>");
document.writeln("		");
document.writeln("			<p class=\'c\'>公司简介|网站地图|艾米体验|手机艾米|集团下属公司</p>");
document.writeln("			<p>Copyright (C) 艾米网 2004-2017, All Rights <br />Reserved增值图书业务经营许可证：粤B2-20120350&nbsp;&nbsp; 粤ICP备05087105号&nbsp;&nbsp;  <br />");
document.writeln("			粤网文[2015]2233-484号&nbsp;&nbsp;粤文市审[2012]196号&nbsp;&nbsp;");
document.writeln("			</p>");
document.writeln("			<span class=\'ic\'><img src=\'images/zhandian/zahndian1.png\' />");
document.writeln("			<img src=\'images/zhandian/zhandian2.png\' /></span>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("</div>");